### PR TITLE
Fixes missing item image #3

### LINKED ISSUE #3: #INC-5312: Missing image
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

### PR DESCRIPTION
**Pull request by AsafSH6**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @AsafSH6, I'll review the changes right away!

**Comment by AsafSH6** [comment]
image

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @AsafSH6! You're now able to merge the PR.

**Pull request merged**
